server:
  port: 8780
eureka:
  instance:
    preferIpAddress: true
    ip-address: 120.197.216.203
    #lease-renewal-interval-in-seconds: 3
    #lease-expiration-duration-in-seconds: 10
spring:
  datasource:
      name: datasource-yorkwell
      #url: jdbc:sqlserver://183.62.139.231:19876;DatabaseName=DtradeNetGarmentYorkwell
      url: jdbc:sqlserver://192.168.2.20:1433;DatabaseName=DtradeNetGarmentTest
      username: '{cipher}47002453a64b9a49840f6aea799fdd03bf39544f4557cd77093d89657064e5bf'
      password: '{cipher}297281007f378e334a3ba46c59424404cd28481c8b9ce66da184fd67f23a4ddb'
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

myprofileinfo: this is datatransfer-yorkwell-cn-test default profile

myconfig:
  weixin_web_base_url: http://dtraderp.com/Weixin
  weixin_rest_base_url: http://my.eureka.gateway.zuul.com:8766/weixin-rest/rest
  weixin_import_url_maps:
    mpoexcessconfirm: /Mpo/Import/MpoExcessConfirm?companycode={companycode}&batchpushid={batchpushid}&uploadall={uploadall}
    jobmatstatus: /Job/Import/JobMatStatus?companycode={companycode}&batchpushid={batchpushid}&uploadall={uploadall}
    ordercompleteprocess: /Order/Import/OrderCompleteProcess?companycode={companycode}&batchpushid={batchpushid}&uploadall={uploadall}
  erp_approve_url_maps:
    mpoexcessconfirm: 
    jobmatstatus: 
  #my weixin account
  weixin:
    appid: 
    appsecret: 
    upload-filepath: D:/WeixinTemp/Files
    log-filepath: D:/WeixinTemp/Log
  weixin_template_maps:
    mpoexcessconfirm: EwaCZmKWc1aPSUxncwZiMe-iAQ5OhKchr4v7A0gacS4
    